---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/activities":
    post:
      summary: create activity
      tags:
      - Activities
      security:
      - bearer_auth: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              examples:
                activity:
                  value:
                    id: 1
                    day_id: 3
                    date: '2023-04-06T15:17:11.126Z'
                    created_at: '2023-04-06T15:17:11.136Z'
                    updated_at: '2023-04-06T15:17:11.136Z'
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  day_id:
                    type: integer
                  date:
                    type: datetime
                    nullable: false
                  created_at:
                    type: datetime
                    nullable: false
                  updated_at:
                    type: datetime
                    nullable: false
  "/api/v1/activities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete activity
      tags:
      - Activities
      security:
      - bearer_auth: []
      responses:
        '204':
          description: no content
        '404':
          description: not found
  "/api/v1/days":
    get:
      summary: list days
      tags:
      - Days
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                no_days: {}
                days:
                  value:
                  - id: 4
                    date: '2023-03-28T22:00:00.000Z'
                    created_at: '2023-03-29T14:10:43.226Z'
                    updated_at: '2023-03-29T14:10:43.226Z'
                  - id: 2
                    date: '2023-04-04T22:00:00.000Z'
                    created_at: '2023-04-05T19:41:08.528Z'
                    updated_at: '2023-04-05T19:41:08.528Z'
    post:
      summary: create day
      tags:
      - Days
      security:
      - bearer_auth: []
      responses:
        '201':
          description: created
          content:
            application/json:
              examples:
                day:
                  value:
                    id: 4
                    date: '2023-03-28T22:00:00.000Z'
                    created_at: '2023-03-29T14:10:43.226Z'
                    updated_at: '2023-03-29T14:10:43.226Z'
        '422':
          description: unprocessable entity
          content:
            application/json:
              examples:
                date:
                  value:
                    date:
                    - has already been taken
  "/api/v1/days/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show day
      tags:
      - Days
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                day:
                  value:
                    id: 4
                    date: '2023-03-28T22:00:00.000Z'
                    created_at: '2023-03-29T14:10:43.226Z'
                    updated_at: '2023-03-29T14:10:43.226Z'
    delete:
      summary: delete day
      tags:
      - Days
      security:
      - bearer_auth: []
      responses:
        '204':
          description: no content
        '404':
          description: not found
  "/api/v1/hydrations":
    post:
      summary: create hydration
      tags:
      - Hydrations
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              examples:
                hydration:
                  value:
                    id: 1
                    cups: 0
                    created_at: '2023-04-07T19:29:10.893Z'
                    updated_at: '2023-04-07T19:29:10.893Z'
                    day_id: 4
        '422':
          description: unprocessable entity
          content:
            application/json:
              examples:
                hydration:
                  value:
                    cups:
                    - must be greater than or equal to 0
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cups:
                  type: integer
  "/api/v1/hydrations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update hydration
      tags:
      - Hydrations
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                hydration:
                  value:
                    cups: 0
                    id: 4
                    created_at: '2023-04-07T19:48:40.535Z'
                    updated_at: '2023-04-07T19:48:48.921Z'
                    day_id: 4
        '404':
          description: not found
        '422':
          description: unprocessable entity
          content:
            application/json:
              examples:
                hydration:
                  value:
                    cups:
                    - must be greater than or equal to 0
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cups:
                  type: integer
    put:
      summary: update hydration
      tags:
      - Hydrations
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                hydration:
                  value:
                    cups: 0
                    id: 4
                    created_at: '2023-04-07T19:48:40.535Z'
                    updated_at: '2023-04-07T19:48:48.921Z'
                    day_id: 4
        '404':
          description: not found
        '422':
          description: unprocessable entity
          content:
            application/json:
              examples:
                hydration:
                  value:
                    cups:
                    - must be greater than or equal to 0
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cups:
                  type: integer
    delete:
      summary: delete hydration
      tags:
      - Hydrations
      security:
      - bearer_auth: []
      responses:
        '204':
          description: no content
        '404':
          description: not found
  "/api/v1/sleeps":
    post:
      summary: create sleep
      tags:
      - Sleeps
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              examples:
                sleep:
                  value:
                    id: 1
                    length: '2000-01-01T15:52:28.298Z'
                    created_at: '2023-04-06T15:24:47.632Z'
                    updated_at: '2023-04-06T15:24:47.632Z'
                    day_id: 3
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  length:
                    type: datetime
                    nullable: true
                  created_at:
                    type: datetime
                    nullable: false
                  updated_at:
                    type: datetime
                    nullable: false
                  day_id:
                    type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                length:
                  type: string
                  format: datetime
  "/api/v1/sleeps/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete sleep
      tags:
      - Sleeps
      security:
      - bearer_auth: []
      responses:
        '204':
          description: no content
        '404':
          description: not found
  "/users/sign_in":
    get:
      summary: before sign in
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                user:
                  value:
                    message: You are logged in.
    post:
      summary: sign in
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: success
          headers:
            Authorization:
              schema:
                type: string
                nullable: false
              description: "JWT token that is required to proceed to other pages authorized,
                \n                                it looks like this: \"Authorization:
                Bearer generated.jwt.token\""
        '401':
          description: wrong parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      default: email@example.com
                    password:
                      type: string
                      default: Password1
                  required:
                  - email
                  - password
  "/users/sign_out":
    delete:
      summary: sign out
      tags:
      - Users
      security:
      - bearer_auth: []
      responses:
        '200':
          description: success
          content:
            application/json:
              examples:
                user:
                  value:
                    message: You are logged out.
        '401':
          description: unauthorized (not logged in)
          content:
            application/json:
              examples:
                user:
                  value:
                    message: Hmm nothing happened.
  "/users":
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful creation
          headers:
            Authorization:
              schema:
                type: string
                nullable: false
              description: "JWT token that is required to proceed to other pages authorized,
                \n                                it looks like this: \"Authorization:
                Bearer generated.jwt.token\""
          content:
            application/json:
              examples:
                user:
                  value:
                    message: Signed up sucessfully.
        '422':
          description: unprocessable entity (wrong parameters)
          content:
            application/json:
              examples:
                user:
                  value:
                    email:
                    - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      default: Student99
                    password:
                      type: string
                      default: Password1
                    password_confirmation:
                      type: string
                      default: Password1
                  required:
                  - username
                  - password
                  - password_confirmation
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
